/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.5
 * Generated at: 2024-04-10 03:51:45 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class contact_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("	<head>\n");
      out.write("		<meta charset=\"utf-8\">\n");
      out.write("		<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n");
      out.write("		<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("		 <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->\n");
      out.write("\n");
      out.write("		<title>HTML Education Template</title>\n");
      out.write("\n");
      out.write("		<!-- Google font -->\n");
      out.write("		<link href=\"https://fonts.googleapis.com/css?family=Lato:700%7CMontserrat:400,600\" rel=\"stylesheet\">\n");
      out.write("\n");
      out.write("		<!-- Bootstrap -->\n");
      out.write("		<link type=\"text/css\" rel=\"stylesheet\" href=\"css/bootstrap.min.css\"/>\n");
      out.write("\n");
      out.write("		<!-- Font Awesome Icon -->\n");
      out.write("		<link rel=\"stylesheet\" href=\"css/font-awesome.min.css\">\n");
      out.write("\n");
      out.write("		<!-- Custom stlylesheet -->\n");
      out.write("		<link type=\"text/css\" rel=\"stylesheet\" href=\"css/style.css\"/>\n");
      out.write("\n");
      out.write("		<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->\n");
      out.write("		<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->\n");
      out.write("		<!--[if lt IE 9]>\n");
      out.write("		  <script src=\"https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js\"></script>\n");
      out.write("		  <script src=\"https://oss.maxcdn.com/respond/1.4.2/respond.min.js\"></script>\n");
      out.write("		<![endif]-->\n");
      out.write("\n");
      out.write("\n");
      out.write("		<script>\n");
      out.write("			function validate()\n");
      out.write("			  {\n");
      out.write("				var name=document.regform.name;\n");
      out.write("				if(name.value.length<=0)\n");
      out.write("			   {\n");
      out.write("				  alert(\" Name is Mandatory\");\n");
      out.write("				 name.focus();\n");
      out.write("				 return false;\n");
      out.write("				  }\n");
      out.write("			  \n");
      out.write("				\n");
      out.write("			  \n");
      out.write("		  \n");
      out.write("			  let number=document.regform.number;\n");
      out.write("				if(number.value.length!==10)\n");
      out.write("			  {\n");
      out.write("				  alert(\"Enter 10 Digit Mobile Number\");\n");
      out.write("				 num.focus();\n");
      out.write("				 return false;\n");
      out.write("			  }\n");
      out.write("		  \n");
      out.write("			var email=document.regform.email;\n");
      out.write("			if(email.value.length<=0)\n");
      out.write("		  {\n");
      out.write("			  alert(\"Eamil is Mandatory\");\n");
      out.write("			 email.focus();\n");
      out.write("			 return false;\n");
      out.write("		  }\n");
      out.write("\n");
      out.write("		  var sub=document.regform.subject;\n");
      out.write("		  if(sub.value.length<=0)\n");
      out.write("		  {\n");
      out.write("			alert(\"Please Enter Subject\");\n");
      out.write("			sub.focus();\n");
      out.write("			return false;\n");
      out.write("		  }\n");
      out.write("		   \n");
      out.write("		  var msg=document.regform.message;\n");
      out.write("		  if(msg.value.length<=0)\n");
      out.write("		  {\n");
      out.write("			alert(\"Please write message\");\n");
      out.write("			msg.focus();\n");
      out.write("			return false;\n");
      out.write("		  }\n");
      out.write("\n");
      out.write("		  \n");
      out.write("		  \n");
      out.write("		  \n");
      out.write("		  \n");
      out.write("			  alert (\"Submitted Successfully\");\n");
      out.write("		  		   \n");
      out.write("				  \n");
      out.write("			  } \n");
      out.write("		  \n");
      out.write("		  \n");
      out.write("			  </script>\n");
      out.write("\n");
      out.write("    </head>\n");
      out.write("	<body>\n");
      out.write("\n");
      out.write("		<!-- Header -->\n");
      out.write("		<header id=\"header\">\n");
      out.write("			<div class=\"container\">\n");
      out.write("\n");
      out.write("				<div class=\"navbar-header\">\n");
      out.write("					<!-- Logo -->\n");
      out.write("					<div class=\"navbar-brand\">\n");
      out.write("						<a class=\"logo\" href=\"index.html\">\n");
      out.write("							<img src=\"./img/logo.png\" alt=\"logo\">\n");
      out.write("						</a>\n");
      out.write("					</div>\n");
      out.write("					<!-- /Logo -->\n");
      out.write("\n");
      out.write("					<!-- Mobile toggle -->\n");
      out.write("					<button class=\"navbar-toggle\">\n");
      out.write("						<span></span>\n");
      out.write("					</button>\n");
      out.write("					<!-- /Mobile toggle -->\n");
      out.write("				</div>\n");
      out.write("\n");
      out.write("				<!-- Navigation -->\n");
      out.write("				<nav id=\"nav\">\n");
      out.write("					<ul class=\"main-menu nav navbar-nav navbar-right\">\n");
      out.write("						<li><a href=\"index.jsp\">Home</a></li>\n");
      out.write("						\n");
      out.write("						<li><a href=\"contact.jsp\">Contact</a></li>\n");
      out.write("					</ul>\n");
      out.write("				</nav>\n");
      out.write("				<!-- /Navigation -->\n");
      out.write("\n");
      out.write("			</div>\n");
      out.write("		</header>\n");
      out.write("		<!-- /Header -->\n");
      out.write("\n");
      out.write("		<!-- Hero-area -->\n");
      out.write("		<div class=\"hero-area section\">\n");
      out.write("\n");
      out.write("			<!-- Backgound Image -->\n");
      out.write("			<div class=\"bg-image bg-parallax overlay\" style=\"background-image:url(./img/page-background.jpg)\"></div>\n");
      out.write("			<!-- /Backgound Image -->\n");
      out.write("\n");
      out.write("			<div class=\"container\">\n");
      out.write("				<div class=\"row\">\n");
      out.write("					<div class=\"col-md-10 col-md-offset-1 text-center\">\n");
      out.write("						<ul class=\"hero-area-tree\">\n");
      out.write("							<li><a href=\"index.jsp\">Home</a></li>\n");
      out.write("							<li>Contact</li>\n");
      out.write("						</ul>\n");
      out.write("						<h1 class=\"white-text\">Get In Touch</h1>\n");
      out.write("\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("\n");
      out.write("		</div>\n");
      out.write("		<!-- /Hero-area -->\n");
      out.write("\n");
      out.write("		<!-- Contact -->\n");
      out.write("		<div id=\"contact\" class=\"section\">\n");
      out.write("\n");
      out.write("			<!-- container -->\n");
      out.write("			<div class=\"container\">\n");
      out.write("\n");
      out.write("				<!-- row -->\n");
      out.write("				<div class=\"row\">\n");
      out.write("\n");
      out.write("					<!-- contact form -->\n");
      out.write("					<div class=\"col-md-6\">\n");
      out.write("						<div class=\"contact-form\">\n");
      out.write("							<h4>Send A Message</h4>\n");
      out.write("							<form method=\"post\" action=\"send\" name=\"regform\"  >\n");
      out.write("								<input class=\"input\" type=\"text\" name=\"name\" placeholder=\"Name\">\n");
      out.write("								<input class=\"input\" type=\"number\" name=\"number\" placeholder=\"Mobile Number\">\n");
      out.write("								<input class=\"input\" type=\"email\" name=\"email\" placeholder=\"Email\">\n");
      out.write("								<input class=\"input\" type=\"text\" name=\"subject\" placeholder=\"Subject\">\n");
      out.write("								<textarea class=\"input\" name=\"message\" placeholder=\"Enter your Message\"></textarea>\n");
      out.write("								<button class=\"main-button icon-button pull-right\" value=\"send\">Send Message</button>\n");
      out.write("							</form>\n");
      out.write("						</div>\n");
      out.write("					</div>\n");
      out.write("					<!-- /contact form -->\n");
      out.write("\n");
      out.write("					<!-- contact information -->\n");
      out.write("					<div class=\"col-md-5 col-md-offset-1\">\n");
      out.write("						<h4>Contact Information</h4>\n");
      out.write("						<ul class=\"contact-details\">\n");
      out.write("							<li><i class=\"fa fa-envelope\"></i>gcompnira@gmail.com</li>\n");
      out.write("							<li><i class=\"fa fa-phone\"></i>9422300281 / 9850763226</li>\n");
      out.write("							<li><i class=\"fa fa-map-marker\"></i>Market Yard, Nira</li>\n");
      out.write("						</ul>\n");
      out.write("\n");
      out.write("						<!-- contact map -->\n");
      out.write("						<div id=\"contact-map\"></div>\n");
      out.write("						<!-- /contact map -->\n");
      out.write("\n");
      out.write("					</div>\n");
      out.write("					<!-- contact information -->\n");
      out.write("\n");
      out.write("				</div>\n");
      out.write("				<!-- /row -->\n");
      out.write("\n");
      out.write("			</div>\n");
      out.write("			<!-- /container -->\n");
      out.write("\n");
      out.write("		</div>\n");
      out.write("		<!-- /Contact -->\n");
      out.write("\n");
      out.write("		<!-- Footer -->\n");
      out.write("		<footer id=\"footer\" class=\"section\">\n");
      out.write("\n");
      out.write("			<!-- container -->\n");
      out.write("			<div class=\"container\">\n");
      out.write("\n");
      out.write("				<!-- row -->\n");
      out.write("				<div class=\"row\">\n");
      out.write("\n");
      out.write("					<!-- footer logo -->\n");
      out.write("					<div class=\"col-md-6\">\n");
      out.write("						<div class=\"footer-logo\">\n");
      out.write("							<a class=\"logo\" href=\"index.jsp\">\n");
      out.write("								<img src=\"./img/logo.png\" alt=\"logo\">\n");
      out.write("							</a>\n");
      out.write("						</div>\n");
      out.write("					</div>\n");
      out.write("					<!-- footer logo -->\n");
      out.write("\n");
      out.write("					<!-- footer nav -->\n");
      out.write("					<div class=\"col-md-6\">\n");
      out.write("						<ul class=\"footer-nav\">\n");
      out.write("							<li><a href=\"index.jsp\">Home</a></li>\n");
      out.write("							\n");
      out.write("							<li><a href=\"contact.jsp\">Contact</a></li>\n");
      out.write("						</ul>\n");
      out.write("					</div>\n");
      out.write("					<!-- /footer nav -->\n");
      out.write("\n");
      out.write("				</div>\n");
      out.write("				<!-- /row -->\n");
      out.write("\n");
      out.write("				<!-- row -->\n");
      out.write("				<div id=\"bottom-footer\" class=\"row\">\n");
      out.write("\n");
      out.write("					\n");
      out.write("\n");
      out.write("					\n");
      out.write("\n");
      out.write("				</div>\n");
      out.write("				<!-- row -->\n");
      out.write("\n");
      out.write("			</div>\n");
      out.write("			<!-- /container -->\n");
      out.write("\n");
      out.write("		</footer>\n");
      out.write("		<!-- /Footer -->\n");
      out.write("\n");
      out.write("		<!-- preloader -->\n");
      out.write("		<div id='preloader'><div class='preloader'></div></div>\n");
      out.write("		<!-- /preloader -->\n");
      out.write("\n");
      out.write("\n");
      out.write("		<!-- jQuery Plugins -->\n");
      out.write("		<script type=\"text/javascript\" src=\"js/jquery.min.js\"></script>\n");
      out.write("		<script type=\"text/javascript\" src=\"js/bootstrap.min.js\"></script>\n");
      out.write("		<script src=\"https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false\"></script>\n");
      out.write("		<script type=\"text/javascript\" src=\"js/google-map.js\"></script>\n");
      out.write("		<script type=\"text/javascript\" src=\"js/main.js\"></script>\n");
      out.write("\n");
      out.write("	</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
